#! /bin/bash

declare -A URL
declare -A CMD
declare -A TEST

URL["ape"]="https://cran.r-project.org/web/packages/ape/ape.pdf \
            https://cran.r-project.org/web/packages/ape/vignettes/DrawingPhylogenies.pdf \
            https://cran.r-project.org/web/packages/ape/vignettes/MoranI.pdf \
            https://cran.r-project.org/web/packages/ape/vignettes/RandomTopologies.pdf"
CMD["ape"]="Rscript -e 'if (system.file(package=\"ape\") != \"\") {v <- packageVersion(\"ape\"); cat(toString(v))}'"
TEST["ape"]=5.7.1

URL["armadillo"]="http://arma.sourceforge.net/docs.html"
CMD["armadillo"]="pkg-config --modversion armadillo"
TEST["armadillo"]=11.0.0

URL["assertthat"]="https://cran.r-project.org/web/packages/assertthat/assertthat.pdf"
CMD["assertthat"]="Rscript -e 'if (system.file(package=\"assertthat\") != \"\") {v <- packageVersion(\"assertthat\"); cat(toString(v))}'"
TEST["assertthat"]=0.2.1

URL["awk"]="https://www.gnu.org/software/gawk/manual/gawk.pdf"
CMD["awk"]="awk --version"
TEST["awk"]=5.1.1

URL["bash"]="https://www.gnu.org/software/bash/manual/bash.pdf"
CMD["bash"]="bash --version"
TEST["bash"]=5.1.16

URL["bc"]="https://www.gnu.org/software/bc/manual/html_mono/bc.html"
CMD["bc"]="bc --version"
TEST["bc"]=1.07.1

URL["beautifulsoup"]="https://beautiful-soup-4.readthedocs.io/_/downloads/en/latest/pdf/"
CMD["beautifulsoup"]="python -c 'from bs4 import __version__ as v; print(v)'"
TEST["beautifulsoup"]=4.12.2

URL["beets"]="https://beets.readthedocs.io/_/downloads/en/vMAJOR.MINOR.PATCH/pdf/"
CMD["beets"]="python -c 'from beets import __version__ as v; print(v)'"
TEST["beets"]=1.6.0

URL["biopython"]="https://biopython.org/DIST/docs/tutorial/Tutorial-MAJOR.MINOR.pdf"
CMD["biopython"]="python -c 'from Bio import __version__ as v; print(v)'"
TEST["biopython"]=1.79

URL["bipartite"]="https://cran.r-project.org/web/packages/bipartite/bipartite.pdf"
CMD["bipartite"]="Rscript -e 'if (system.file(package=\"bipartite\") != \"\") {v <- packageVersion(\"bipartite\"); cat(toString(v))}'"
TEST["bipartite"]=2.18

URL["black"]="https://black.readthedocs.io/_/downloads/en/latest/htmlzip/"
CMD["black"]="python -c 'from black import __version__ as v; print(v)'"
TEST["black"]=23.7.0

URL["coreutils"]="https://www.gnu.org/software/coreutils/manual/coreutils.pdf"
CMD["coreutils"]="ls --version"
TEST["coreutils"]=9.0

URL["curl"]="https://cran.r-project.org/web/packages/curl/curl.pdf \
             https://cran.r-project.org/web/packages/curl/vignettes/intro.html \
             https://cran.r-project.org/web/packages/curl/vignettes/windows.html"
CMD["curl"]="Rscript -e 'if (system.file(package=\"curl\") != \"\") {v <- packageVersion(\"curl\"); cat(toString(v))}'"
TEST["curl"]=5.0.2

URL["data.table"]="https://cran.r-project.org/web/packages/data.table/data.table.pdf \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-benchmarking.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-keys-fast-subset.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reference-semantics.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reshape.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-sd-usage.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-secondary-indices-and-auto-indexing.html \
                   https://raw.githubusercontent.com/rstudio/cheatsheets/master/datatable.pdf"
CMD["data.table"]="Rscript -e 'if (system.file(package=\"data.table\") != \"\") {v <- packageVersion(\"data.table\"); cat(toString(v))}'"
TEST["data.table"]=1.14.8

URL["devtools"]="https://cran.r-project.org/web/packages/devtools/devtools.pdf \
                 https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html"
CMD["devtools"]="Rscript -e 'if (system.file(package=\"devtools\") != \"\") {v <- packageVersion(\"devtools\"); cat(toString(v))}'"
TEST["devtools"]=2.4.5

URL["dplyr"]="https://cran.r-project.org/web/packages/dplyr/dplyr.pdf \
              https://cran.r-project.org/web/packages/dplyr/vignettes/base.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/colwise.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/grouping.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/in-packages.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/rowwise.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/window-functions.html \
              https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-transformation.pdf"
CMD["dplyr"]="Rscript -e 'if (system.file(package=\"dplyr\") != \"\") {v <- packageVersion(\"dplyr\"); cat(toString(v))}'"
TEST["dplyr"]=1.1.2

URL["eigen"]="https://eigen.tuxfamily.org/dox/eigen-doc.tgz"
CMD["eigen"]="pkg-config --modversion eigen3"
TEST["eigen"]=3.4.0

URL["expm"]="https://cran.r-project.org/web/packages/expm/expm.pdf \
             https://cran.r-project.org/web/packages/expm/vignettes/expm.pdf"
CMD["expm"]="Rscript -e 'if (system.file(package=\"expm\") != \"\") {v <- packageVersion(\"expm\"); cat(toString(v))}'"
TEST["expm"]=0.999.7

URL["ffmpeg"]="https://ffmpeg.org/ffmpeg-all.html"
CMD["ffmpeg"]="ffmpeg -version"
TEST["ffmpeg"]=5.0

URL["find"]="https://www.gnu.org/software/findutils/manual/find.pdf"
CMD["find"]="find --version"
TEST["find"]=4.9.0

URL["fish"]="https://fishshell.com/docs/MAJOR.MINOR/index.html \
             https://fishshell.com/docs/MAJOR.MINOR/tutorial.html"
CMD["fish"]="fish --version"
TEST["fish"]=3.3.1

URL["gcc"]="https://gcc.gnu.org/onlinedocs/gcc-MAJOR.MINOR.0/gcc.pdf \
            https://gcc.gnu.org/onlinedocs/gcc-MAJOR.MINOR.0/libstdc++-manual.pdf.gz"
CMD["gcc"]="gcc --version"
TEST["gcc"]=11.2.0

URL["ggplot"]="https://cran.r-project.org/web/packages/ggplot2/ggplot2.pdf \
               https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html \
               https://cran.r-project.org/web/packages/ggplot2/vignettes/ggplot2-in-packages.html \
               https://cran.r-project.org/web/packages/ggplot2/vignettes/ggplot2-specs.html \
               https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf"
CMD["ggplot"]="Rscript -e 'if (system.file(package=\"ggplot2\") != \"\") {v <- packageVersion(\"ggplot2\"); cat(toString(v))}'"
TEST["ggplot"]=3.4.3

URL["gimp"]="https://download.gimp.org/pub/gimp/help/gimp-help-MAJOR.MINOR.0.tar.bz2"
CMD["gimp"]="gimp --version"
TEST["gimp"]=2.10.30

URL["glmnet"]="https://cran.r-project.org/web/packages/glmnet/glmnet.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/Coxnet.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/glmnet.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/glmnetFamily.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/relax.pdf"
CMD["glmnet"]="Rscript -e 'if (system.file(package=\"glmnet\") != \"\") {v <- packageVersion(\"glmnet\"); cat(toString(v))}'"
TEST["glmnet"]=4.1.8

URL["graphviz"]=""
CMD["graphviz"]="dot -V"
TEST["graphviz"]=3.0.0

URL["igraph"]="https://cran.r-project.org/web/packages/igraph/igraph.pdf \
               https://cran.r-project.org/web/packages/igraph/vignettes/igraph.html"
CMD["igraph"]="Rscript -e 'if (system.file(package=\"igraph\") != \"\") {v <- packageVersion(\"igraph\"); cat(toString(v))}'"
TEST["igraph"]=1.5.1

URL["inkscape"]="https://inkscape-manuals.readthedocs.io/_/downloads/en/latest/pdf/"
CMD["inkscape"]="inkscape --version"
TEST["inkscape"]=1.1.2

URL["interplot"]="https://cran.r-project.org/web/packages/interplot/interplot.pdf \
                  https://cran.r-project.org/web/packages/interplot/vignettes/interplot-vignette.html"
CMD["interplot"]="Rscript -e 'if (system.file(package=\"interplot\") != \"\") {v <- packageVersion(\"interplot\"); cat(toString(v))}'"
TEST["interplot"]=0.2.3

URL["gitpython"]="https://gitpython.readthedocs.io/_/downloads/en/MAJOR.MINOR.PATCH/pdf/"
CMD["gitpython"]="python -c 'from git import __version__ as v; print(v)'"
TEST["gitpython"]=3.1.32

URL["julia"]="https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-MAJOR.MINOR.PATCH.pdf"
CMD["julia"]="julia --version"
TEST["julia"]=1.7.2

URL["knitr"]="https://cran.r-project.org/web/packages/knitr/knitr.pdf \
              https://cran.r-project.org/web/packages/knitr/vignettes/datatables.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knit_expand.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knitr-html.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knitr-markdown.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/docco-classic.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/docco-linear.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knitr-intro.html"
CMD["knitr"]="Rscript -e 'if (system.file(package=\"knitr\") != \"\") {v <- packageVersion(\"knitr\"); cat(toString(v))}'"
TEST["knitr"]=1.43

URL["latex2exp"]="https://cran.r-project.org/web/packages/latex2exp/latex2exp.pdf \
                  https://cran.r-project.org/web/packages/latex2exp/vignettes/supported-commands.html \
                  https://cran.r-project.org/web/packages/latex2exp/vignettes/using-latex2exp.html"
CMD["latex2exp"]="Rscript -e 'if (system.file(package=\"latex2exp\") != \"\") {v <- packageVersion(\"latex2exp\"); cat(toString(v))}'"
TEST["latex2exp"]=0.9.6

URL["lua"]="https://www.lua.org/ftp/refman-MAJOR.MINOR.tar.gz"
CMD["lua"]="lua -v"
TEST["lua"]=5.4

URL["lubridate"]="https://cran.r-project.org/web/packages/lubridate/lubridate.pdf \
                  https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html"
CMD["lubridate"]="Rscript -e 'if (system.file(package=\"lubridate\") != \"\") {v <- packageVersion(\"lubridate\"); cat(toString(v))}'"
TEST["lubridate"]=1.9.2

URL["magic"]="https://magic.readthedocs.io/_/downloads/en/stable/pdf/"
CMD["magic"]="python -c 'import magic; print(magic.version())'"
TEST["magic"]=0.4.27

URL["magrittr"]="https://cran.r-project.org/web/packages/magrittr/magrittr.pdf \
                 https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html \
                 https://cran.r-project.org/web/packages/magrittr/vignettes/tradeoffs.html"
CMD["magrittr"]="Rscript -e 'if (system.file(package=\"magrittr\") != \"\") {v <- packageVersion(\"magrittr\"); cat(toString(v))}'"
TEST["magrittr"]=2.0.3

URL["MASS"]="https://cran.r-project.org/web/packages/MASS/MASS.pdf"
CMD["MASS"]="Rscript -e 'if (system.file(package=\"MASS\") != \"\") {v <- packageVersion(\"MASS\"); cat(toString(v))}'"
TEST["MASS"]=7.3.60

URL["matplotlib"]="https://matplotlib.org/MAJOR.MINOR.PATCH/Matplotlib.pdf"
CMD["matplotlib"]="python -c 'from matplotlib import __version__ as v; print(v)'"
TEST["matplotlib"]=3.5.1

URL["mpi4py"]="https://mpi4py.readthedocs.io/_/downloads/en/MAJOR.MINOR.PATCH/pdf/"
CMD["mpi4py"]="python -c 'from mpi4py import __version__ as v; print(v)'"
TEST["mpi4py"]=3.1.4

URL["mvtnorm"]="https://cran.r-project.org/web/packages/mvtnorm/mvtnorm.pdf \
                https://cran.r-project.org/web/packages/mvtnorm/vignettes/MVT_Rnews.pdf \
                https://cran.r-project.org/web/packages/mvtnorm/vignettes/lmvnorm_src.pdf"
CMD["mvtnorm"]="Rscript -e 'if (system.file(package=\"mvtnorm\") != \"\") {v <- packageVersion(\"mvtnorm\"); cat(toString(v))}'"
TEST["mvtnorm"]=1.2.2

URL["nodejs"]="https://nodejs.org/docs/latest-vMAJOR.x/api/all.html"
CMD["nodejs"]="node --version"
TEST["nodejs"]=17.8.0

URL["numpy"]="https://numpy.org/doc/MAJOR.MINOR/numpy-html.zip"
CMD["numpy"]="python -c 'from numpy import __version__ as v; print(v)'"
TEST["numpy"]=1.22

URL["octave"]="https://octave.org/doc/octave-MAJOR.MINOR.PATCH.pdf"
CMD["octave"]="octave --version"
TEST["octave"]=6.4.0

URL["optparse"]="https://cran.r-project.org/web/packages/optparse/optparse.pdf \
                 https://cran.r-project.org/web/packages/optparse/vignettes/optparse.html"
CMD["optparse"]="Rscript -e 'if (system.file(package=\"optparse\") != \"\") {v <- packageVersion(\"optparse\"); cat(toString(v))}'"
TEST["optparse"]=1.7.3

URL["pandas"]="https://pandas.pydata.org/pandas-docs/version/MAJOR.MINOR.PATCH/pandas.zip"
CMD["pandas"]="python -c 'from pandas import __version__ as v; print(v)'"
TEST["pandas"]=1.4.1

URL["patchwork"]="https://cran.r-project.org/web/packages/patchwork/patchwork.pdf \
                  https://cran.r-project.org/web/packages/patchwork/vignettes/patchwork.html"
CMD["patchwork"]="Rscript -e 'if (system.file(package=\"patchwork\") != \"\") {v <- packageVersion(\"patchwork\"); cat(toString(v))}'"
TEST["patchwork"]=1.1.3

URL["parallel"]="https://www.gnu.org/software/parallel/parallel_tutorial.pdf \
                 https://www.gnu.org/software/parallel/parallel.pdf \
                 https://www.gnu.org/software/parallel/parallel_cheat.pdf"
CMD["parallel"]="parallel --version"
TEST["parallel"]=20220322

URL["pillow"]="https://pillow.readthedocs.io/_/downloads/en/stable/pdf/"
CMD["pillow"]="python -c 'from PIL import __version__ as v; print(v)'"
TEST["pillow"]=10.0.0

URL["purrr"]="https://cran.r-project.org/web/packages/purrr/purrr.pdf \
              https://cran.r-project.org/web/packages/purrr/vignettes/base.html \
              https://cran.r-project.org/web/packages/purrr/vignettes/other-langs.html"
CMD["purrr"]="Rscript -e 'if (system.file(package=\"purrr\") != \"\") {v <- packageVersion(\"purrr\"); cat(toString(v))}'"
TEST["purrr"]=1.0.2

URL["python"]="https://docs.python.org/MAJOR.MINOR/archives/python-MAJOR.MINOR.PATCH-docs-pdf-letter.zip"
CMD["python"]="python --version"
TEST["python"]=3.10.3

URL["quadprog"]="https://cran.r-project.org/web/packages/quadprog/quadprog.pdf"
CMD["quadprog"]="Rscript -e 'if (system.file(package=\"quadprog\") != \"\") {v <- packageVersion(\"quadprog\"); cat(toString(v))}'"
TEST["quadprog"]=1.5.8

URL["r"]="https://cran.r-project.org/doc/manuals/r-release/fullrefman.pdf"
CMD["r"]="R --version"
TEST["r"]=4.0.5

URL["rcolorbrewer"]="https://cran.r-project.org/web/packages/RColorBrewer/RColorBrewer.pdf"
CMD["rcolorbrewer"]="Rscript -e 'if (system.file(package=\"rcolorbrewer\") != \"\") {v <- packageVersion(\"rcolorbrewer\"); cat(toString(v))}'"
TEST["rcolorbrewer"]=1.1.3

URL["rcpp"]="https://cran.r-project.org/web/packages/Rcpp/Rcpp.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-attributes.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-extending.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-introduction.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-jss-2011.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-libraries.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-modules.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-package.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-quickref.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-sugar.pdf"
CMD["rcpp"]="Rscript -e 'if (system.file(package=\"rcpp\") != \"\") {v <- packageVersion(\"rcpp\"); cat(toString(v))}'"
TEST["rcpp"]=1.0.11

URL["rcpparmadillo"]="https://cran.r-project.org/web/packages/RcppArmadillo/RcppArmadillo.pdf \
                      https://cran.r-project.org/web/packages/RcppArmadillo/vignettes/RcppArmadillo-intro.pdf \
                      https://cran.r-project.org/web/packages/RcppArmadillo/vignettes/RcppArmadillo-sparseMatrix.pdf"
CMD["rcpparmadillo"]="Rscript -e 'if (system.file(package=\"rcpparmadillo\") != \"\") {v <- packageVersion(\"rcpparmadillo\"); cat(toString(v))}'"
TEST["rcpparmadillo"]=0.12.6.1.0

URL["rcppeigen"]="https://cran.r-project.org/web/packages/RcppEigen/RcppEigen.pdf \
                  https://cran.r-project.org/web/packages/RcppEigen/vignettes/RcppEigen-Introduction.pdf"
CMD["rcppeigen"]="Rscript -e 'if (system.file(package=\"rcppeigen\") != \"\") {v <- packageVersion(\"rcppeigen\"); cat(toString(v))}'"
TEST["rcppeigen"]=0.3.3.9.3

URL["readr"]="https://cran.r-project.org/web/packages/readr/readr.pdf \
              https://cran.r-project.org/web/packages/readr/vignettes/column-types.html \
              https://cran.r-project.org/web/packages/readr/vignettes/locales.html \
              https://cran.r-project.org/web/packages/readr/vignettes/readr.html"
CMD["readr"]="Rscript -e 'if (system.file(package=\"readr\") != \"\") {v <- packageVersion(\"readr\"); cat(toString(v))}'"
TEST["readr"]=2.1.4

URL["reshape2"]="https://cran.r-project.org/web/packages/reshape2/reshape2.pdf"
CMD["reshape2"]="Rscript -e 'if (system.file(package=\"reshape2\") != \"\") {v <- packageVersion(\"reshape2\"); cat(toString(v))}'"
TEST["reshape2"]=1.4.4

URL["rmarkdown"]="https://cran.r-project.org/web/packages/rmarkdown/rmarkdown.pdf"
CMD["rmarkdown"]="Rscript -e 'if (system.file(package=\"rmarkdown\") != \"\") {v <- packageVersion(\"rmarkdown\"); cat(toString(v))}'"
TEST["rmarkdown"]=2.24

URL["rvest"]="https://cran.r-project.org/web/packages/rvest/rvest.pdf \
              https://cran.r-project.org/web/packages/rvest/vignettes/rvest.html \
              https://cran.r-project.org/web/packages/rvest/vignettes/starwars.html"
CMD["rvest"]="Rscript -e 'if (system.file(package=\"rvest\") != \"\") {v <- packageVersion(\"rvest\"); cat(toString(v))}'"
TEST["rvest"]=1.0.3

URL["scipy"]="https://docs.scipy.org/doc/scipy-MAJOR.MINOR.PATCH/scipy-html-MAJOR.MINOR.PATCH.zip"
CMD["scipy"]="python -c 'from scipy import __version__ as v; print(v)'"
TEST["scipy"]=1.8.0

URL["seaborn"]="https://github.com/seaborn/seaborn.github.io/archive/refs/tags/vMAJOR.MINOR.PATCH.zip"
CMD["seaborn"]="python -c 'from seaborn import __version__ as v; print(v)'"
TEST["seaborn"]=0.12.1

URL["sed"]="https://www.gnu.org/software/sed/manual/sed.pdf"
CMD["sed"]="sed --version"
TEST["sed"]=4.8

URL["scrapy"]="https://docs.scrapy.org/_/downloads/en/MAJOR.MINOR/pdf/"
CMD["scrapy"]="python -c 'from scrapy import __version__ as v; print(v)'"
TEST["scrapy"]=2.8

URL["sklearn"]="https://scikit-learn.org/MAJOR.MINOR/_downloads/scikit-learn-docs.zip"
CMD["sklearn"]="python -c 'from sklearn import __version__ as v; print(v)'"
TEST["sklearn"]=1.0.2

URL["stringr"]="https://cran.r-project.org/web/packages/stringr/stringr.pdf \
                https://cran.r-project.org/web/packages/stringr/vignettes/from-base.html \
                https://cran.r-project.org/web/packages/stringr/vignettes/regular-expressions.html \
                https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html"
CMD["stringr"]="Rscript -e 'if (system.file(package=\"stringr\") != \"\") {v <- packageVersion(\"stringr\"); cat(toString(v))}'"
TEST["stringr"]=1.5.0

URL["testthat"]="https://cran.r-project.org/web/packages/testthat/testthat.pdf"
CMD["testthat"]="Rscript -e 'if (system.file(package=\"testthat\") != \"\") {v <- packageVersion(\"testthat\"); cat(toString(v))}'"
TEST["testthat"]=3.1.10

URL["tibble"]="https://cran.r-project.org/web/packages/tibble/tibble.pdf"
CMD["tibble"]="Rscript -e 'if (system.file(package=\"tibble\") != \"\") {v <- packageVersion(\"tibble\"); cat(toString(v))}'"
TEST["tibble"]=3.2.1

URL["tidyr"]="https://cran.r-project.org/web/packages/tidyr/tidyr.pdf"
CMD["tidyr"]="Rscript -e 'if (system.file(package=\"tidyr\") != \"\") {v <- packageVersion(\"tidyr\"); cat(toString(v))}'"
TEST["tidyr"]=1.3.0

URL["tidyverse"]="https://cran.r-project.org/web/packages/tidyverse/tidyverse.pdf"
CMD["tidyverse"]="Rscript -e 'if (system.file(package=\"tidyverse\") != \"\") {v <- packageVersion(\"tidyverse\"); cat(toString(v))}'"
TEST["tidyverse"]=2.0.0

URL["vegan"]="https://cran.r-project.org/web/packages/vegan/vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/decision-vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/diversity-vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/intro-vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/partitioning.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/FAQ-vegan.html"
CMD["vegan"]="Rscript -e 'if (system.file(package=\"vegan\") != \"\") {v <- packageVersion(\"vegan\"); cat(toString(v))}'"
TEST["vegan"]=2.6.4

URL["wget"]="https://www.gnu.org/software/wget/manual/wget.pdf"
CMD["wget"]="wget --version"
TEST["wget"]=1.21.3

URL["zsh"]="https://sourceforge.net/projects/zsh/files/zsh-doc/MAJOR.MINOR.PATCH/zsh-MAJOR.MINOR.PATCH-doc.tar.xz"
CMD["zsh"]="zsh --version"
TEST["zsh"]=5.8.1

export URL
export CMD
export TEST
