#! /bin/bash

function r_cmd {
  cat << EOF
Rscript -e \
'if (system.file(package="${1}") != "") { \
   v <- packageVersion("${1}"); \
   cat(toString(v)); \
 }'
EOF
}

declare -A URL
declare -A CMD
declare -A TEST

URL["ape"]="https://cran.r-project.org/web/packages/ape/ape.pdf \
            https://cran.r-project.org/web/packages/ape/vignettes/DrawingPhylogenies.pdf \
            https://cran.r-project.org/web/packages/ape/vignettes/MoranI.pdf \
            https://cran.r-project.org/web/packages/ape/vignettes/RandomTopologies.pdf"
CMD["ape"]="$(r_cmd "ape")"
TEST["ape"]=5.7.1

URL["armadillo"]="http://arma.sourceforge.net/docs.html"
CMD["armadillo"]="pkg-config --modversion armadillo"
TEST["armadillo"]=11.0.0

URL["assertthat"]="https://cran.r-project.org/web/packages/assertthat/assertthat.pdf"
CMD["assertthat"]="$(r_cmd "assertthat")"
TEST["assertthat"]=0.2.1

URL["automake"]="https://www.gnu.org/software/automake/manual/automake.pdf"
CMD["automake"]="automake --version"
TEST["automake"]=1.16.5

URL["awk"]="https://www.gnu.org/software/gawk/manual/gawk.pdf"
CMD["awk"]="awk --version"
TEST["awk"]=5.1.1

URL["bash"]="https://www.gnu.org/software/bash/manual/bash.pdf"
CMD["bash"]="bash --version"
TEST["bash"]=5.1.16

URL["bc"]="https://www.gnu.org/software/bc/manual/html_mono/bc.html"
CMD["bc"]="bc --version"
TEST["bc"]=1.07.1

URL["beautifulsoup"]="https://beautiful-soup-4.readthedocs.io/_/downloads/en/latest/pdf/"
CMD["beautifulsoup"]="python -c 'from bs4 import __version__ as v; print(v)'"
TEST["beautifulsoup"]=4.12.2

URL["beets"]="https://beets.readthedocs.io/_/downloads/en/vMAJOR.MINOR.PATCH/pdf/"
CMD["beets"]="python -c 'from beets import __version__ as v; print(v)'"
TEST["beets"]=1.6.0

URL["biopython"]="https://biopython.org/DIST/docs/tutorial/Tutorial-MAJOR.MINOR.pdf"
CMD["biopython"]="python -c 'from Bio import __version__ as v; print(v)'"
TEST["biopython"]=1.79

URL["bipartite"]="https://cran.r-project.org/web/packages/bipartite/bipartite.pdf"
CMD["bipartite"]="$(r_cmd "bipartite")"
TEST["bipartite"]=2.18

URL["bison"]="https://www.gnu.org/software/bison/manual/bison.pdf"
CMD["bison"]="bison --version"
TEST["bison"]=3.8.2

URL["black"]="https://black.readthedocs.io/_/downloads/en/latest/htmlzip/"
CMD["black"]="python -c 'from black import __version__ as v; print(v)'"
TEST["black"]=23.7.0

URL["blender"]="https://docs.blender.org/manual/en/MAJOR.MINOR/blender_manual_html.zip"
CMD["blender"]="blender --version"
TEST["blender"]=3.6.0

URL["clang"]="https://releases.llvm.org/16.0.0/tools/clang/docs/UsersManual.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/Toolchain.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/LanguageExtensions.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/ClangCommandLineReference.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/DiagnosticsReference.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/CrossCompilation.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/ClangStaticAnalyzer.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/ThreadSafetyAnalysis.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/StandardCPlusPlusModules.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/Modules.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/OpenCLSupport.html \
              https://releases.llvm.org/16.0.0/tools/clang/docs/OpenMPSupport.html"
CMD["clang"]="clang --version"
TEST["clang"]=15.0.7

URL["coreutils"]="https://www.gnu.org/software/coreutils/manual/coreutils.pdf"
CMD["coreutils"]="ls --version"
TEST["coreutils"]=9.0

URL["curl"]="https://curl.se/docs/manual.html \
             https://curl.se/docs/manpage.html"
CMD["curl"]="curl --version"
TEST["curl"]=8.2.1

URL["data.table"]="https://cran.r-project.org/web/packages/data.table/data.table.pdf \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-benchmarking.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-keys-fast-subset.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reference-semantics.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reshape.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-sd-usage.html \
                   https://cran.r-project.org/web/packages/data.table/vignettes/datatable-secondary-indices-and-auto-indexing.html \
                   https://raw.githubusercontent.com/rstudio/cheatsheets/master/datatable.pdf"
CMD["data.table"]="$(r_cmd "data.table")"
TEST["data.table"]=1.14.8

URL["ddrescue"]="https://www.gnu.org/software/ddrescue/manual/ddrescue_manual.html"
CMD["ddrescue"]="ddrescue --version"
TEST["ddrescue"]=1.27

URL["devtools"]="https://cran.r-project.org/web/packages/devtools/devtools.pdf \
                 https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html"
CMD["devtools"]="$(r_cmd "devtools")"
TEST["devtools"]=2.4.5

URL["diffutils"]="https://www.gnu.org/software/diffutils/manual/diffutils.pdf"
CMD["diffutils"]="diff --version"
TEST["diffutils"]=3.10

URL["dplyr"]="https://cran.r-project.org/web/packages/dplyr/dplyr.pdf \
              https://cran.r-project.org/web/packages/dplyr/vignettes/base.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/colwise.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/grouping.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/in-packages.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/rowwise.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html \
              https://cran.r-project.org/web/packages/dplyr/vignettes/window-functions.html \
              https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-transformation.pdf"
CMD["dplyr"]="$(r_cmd "dplyr")"
TEST["dplyr"]=1.1.2

URL["eigen"]="https://eigen.tuxfamily.org/dox/eigen-doc.tgz"
CMD["eigen"]="pkg-config --modversion eigen3"
TEST["eigen"]=3.4.0

URL["expm"]="https://cran.r-project.org/web/packages/expm/expm.pdf \
             https://cran.r-project.org/web/packages/expm/vignettes/expm.pdf"
CMD["expm"]="$(r_cmd "expm")"
TEST["expm"]=0.999.7

URL["ffmpeg"]="https://ffmpeg.org/ffmpeg-all.html"
CMD["ffmpeg"]="ffmpeg -version"
TEST["ffmpeg"]=5.0

URL["find"]="https://www.gnu.org/software/findutils/manual/find.pdf"
CMD["find"]="find --version"
TEST["find"]=4.9.0

URL["fish"]="https://fishshell.com/docs/MAJOR.MINOR/index.html \
             https://fishshell.com/docs/MAJOR.MINOR/tutorial.html"
CMD["fish"]="fish --version"
TEST["fish"]=3.3.1

URL["gcc"]="https://gcc.gnu.org/onlinedocs/gcc-MAJOR.MINOR.0/gcc.pdf \
            https://gcc.gnu.org/onlinedocs/gcc-MAJOR.MINOR.0/libstdc++-manual.pdf.gz \
            https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.pdf"
CMD["gcc"]="gcc --version"
TEST["gcc"]=11.2.0

URL["gdb"]="https://sourceware.org/gdb/download/onlinedocs/gdb.pdf"
CMD["gdb"]="gdb --version"
TEST["gdb"]=13.2

URL["ggplot"]="https://cran.r-project.org/web/packages/ggplot2/ggplot2.pdf \
               https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html \
               https://cran.r-project.org/web/packages/ggplot2/vignettes/ggplot2-in-packages.html \
               https://cran.r-project.org/web/packages/ggplot2/vignettes/ggplot2-specs.html \
               https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf"
CMD["ggplot"]="$(r_cmd "ggplot2")"
TEST["ggplot"]=3.4.3

# https://download.gimp.org/mirror/pub/gimp/help/gimp-help-2.10.34.tar.bz2
URL["gimp"]="https://download.gimp.org/pub/gimp/help/gimp-help-MAJOR.MINOR.0.tar.bz2"
CMD["gimp"]="gimp --version"
TEST["gimp"]=2.10.30

URL["git"]="https://github.com/progit/progit2/releases/download/2.1.406/progit.pdf \
            https://training.github.com/downloads/github-git-cheat-sheet.pdf"
CMD["git"]="git --version"
TEST["git"]=2.42.0

URL["glibc"]="https://www.gnu.org/software/libc/manual/MAJOR.MINOR/pdf/libc.pdf"
CMD["glibc"]="ldd --version"
TEST["glibc"]=2.38

URL["glmnet"]="https://cran.r-project.org/web/packages/glmnet/glmnet.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/Coxnet.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/glmnet.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/glmnetFamily.pdf \
               https://cran.r-project.org/web/packages/glmnet/vignettes/relax.pdf"
CMD["glmnet"]="$(r_cmd "glmnet")"
TEST["glmnet"]=4.1.8

URL["grep"]="https://www.gnu.org/software/grep/manual/grep.pdf"
CMD["grep"]="grep --version"
TEST["grep"]=3.11

URL["gsl"]="https://www.gnu.org/software/gsl/doc/latex/gsl-ref.pdf"
CMD["gsl"]="pkg-config --modversion gsl"
TEST["gsl"]=2.7.1

URL["igraph"]="https://cran.r-project.org/web/packages/igraph/igraph.pdf \
               https://cran.r-project.org/web/packages/igraph/vignettes/igraph.html"
CMD["igraph"]="$(r_cmd "igraph")"
TEST["igraph"]=1.5.1

URL["imagemagick"]="https://imagemagick.org/script/command-line-processing.php \
                    https://imagemagick.org/script/command-line-options.php"
CMD["imagemagick"]="magick -version"
TEST["imagemagick"]=7.1.1

URL["inkscape"]="https://inkscape-manuals.readthedocs.io/_/downloads/en/latest/pdf/"
CMD["inkscape"]="inkscape --version"
TEST["inkscape"]=1.1.2

URL["interplot"]="https://cran.r-project.org/web/packages/interplot/interplot.pdf \
                  https://cran.r-project.org/web/packages/interplot/vignettes/interplot-vignette.html"
CMD["interplot"]="$(r_cmd "interplot")"
TEST["interplot"]=0.2.3

URL["gitpython"]="https://gitpython.readthedocs.io/_/downloads/en/MAJOR.MINOR.PATCH/pdf/"
CMD["gitpython"]="python -c 'from git import __version__ as v; print(v)'"
TEST["gitpython"]=3.1.32

URL["jq"]="https://jqlang.github.io/jq/manual/v1.6/"
CMD["jq"]="jq --version"
TEST["jq"]=1.6

URL["julia"]="https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-MAJOR.MINOR.PATCH.pdf"
CMD["julia"]="julia --version"
TEST["julia"]=1.7.2

URL["knitr"]="https://cran.r-project.org/web/packages/knitr/knitr.pdf \
              https://cran.r-project.org/web/packages/knitr/vignettes/datatables.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knit_expand.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knitr-html.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knitr-markdown.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/docco-classic.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/docco-linear.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html \
              https://cran.r-project.org/web/packages/knitr/vignettes/knitr-intro.html"
CMD["knitr"]="$(r_cmd "knitr")"
TEST["knitr"]=1.43

URL["latex2exp"]="https://cran.r-project.org/web/packages/latex2exp/latex2exp.pdf \
                  https://cran.r-project.org/web/packages/latex2exp/vignettes/supported-commands.html \
                  https://cran.r-project.org/web/packages/latex2exp/vignettes/using-latex2exp.html"
CMD["latex2exp"]="$(r_cmd "latex2exp")"
TEST["latex2exp"]=0.9.6

URL["lua"]="https://www.lua.org/ftp/refman-MAJOR.MINOR.tar.gz"
CMD["lua"]="lua -v"
TEST["lua"]=5.4

URL["lubridate"]="https://cran.r-project.org/web/packages/lubridate/lubridate.pdf \
                  https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html"
CMD["lubridate"]="$(r_cmd "lubridate")"
TEST["lubridate"]=1.9.2

URL["magic"]="https://magic.readthedocs.io/_/downloads/en/stable/pdf/"
CMD["magic"]="python -c 'import magic; print(magic.version())'"
TEST["magic"]=0.4.27

URL["magrittr"]="https://cran.r-project.org/web/packages/magrittr/magrittr.pdf \
                 https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html \
                 https://cran.r-project.org/web/packages/magrittr/vignettes/tradeoffs.html"
CMD["magrittr"]="$(r_cmd "magrittr")"
TEST["magrittr"]=2.0.3

URL["MASS"]="https://cran.r-project.org/web/packages/MASS/MASS.pdf"
CMD["MASS"]="$(r_cmd "MASS")"
TEST["MASS"]=7.3.60

URL["make"]="https://www.gnu.org/software/make/manual/make.pdf"
CMD["make"]="make --version"
TEST["make"]=4.4.1

URL["matplotlib"]="https://matplotlib.org/MAJOR.MINOR.PATCH/Matplotlib.pdf"
CMD["matplotlib"]="python -c 'from matplotlib import __version__ as v; print(v)'"
TEST["matplotlib"]=3.5.1

URL["meson"]=""
CMD["meson"]="meson --version"
TEST["meson"]=1.2.1

URL["mpi4py"]="https://mpi4py.readthedocs.io/_/downloads/en/MAJOR.MINOR.PATCH/pdf/"
CMD["mpi4py"]="python -c 'from mpi4py import __version__ as v; print(v)'"
TEST["mpi4py"]=3.1.4

URL["mpv"]="https://mpv.io/manual/stable/"
CMD["mpv"]="mpv --version"
TEST["mpv"]=0.36.0

URL["mvtnorm"]="https://cran.r-project.org/web/packages/mvtnorm/mvtnorm.pdf \
                https://cran.r-project.org/web/packages/mvtnorm/vignettes/MVT_Rnews.pdf \
                https://cran.r-project.org/web/packages/mvtnorm/vignettes/lmvnorm_src.pdf"
CMD["mvtnorm"]="$(r_cmd "mvtnorm")"
TEST["mvtnorm"]=1.2.2

URL["nodejs"]="https://nodejs.org/docs/latest-vMAJOR.x/api/all.html"
CMD["nodejs"]="node --version"
TEST["nodejs"]=17.8.0

URL["numpy"]="https://numpy.org/doc/MAJOR.MINOR/numpy-html.zip"
CMD["numpy"]="python -c 'from numpy import __version__ as v; print(v)'"
TEST["numpy"]=1.22

URL["octave"]="https://octave.org/doc/octave-MAJOR.MINOR.PATCH.pdf"
CMD["octave"]="octave --version"
TEST["octave"]=6.4.0

URL["optparse"]="https://cran.r-project.org/web/packages/optparse/optparse.pdf \
                 https://cran.r-project.org/web/packages/optparse/vignettes/optparse.html"
CMD["optparse"]="$(r_cmd "optparse")"
TEST["optparse"]=1.7.3

URL["pandas"]="https://pandas.pydata.org/pandas-docs/version/MAJOR.MINOR.PATCH/pandas.zip"
CMD["pandas"]="python -c 'from pandas import __version__ as v; print(v)'"
TEST["pandas"]=1.4.1

URL["pandoc"]="https://pandoc.org/MANUAL.pdf"
CMD["pandoc"]="pandoc --version"
TEST["pandoc"]=3.1.2

URL["parted"]="https://www.gnu.org/software/parted/manual/parted.pdf"
CMD["parted"]="parted --version"
TEST["parted"]=3.6

URL["patchwork"]="https://cran.r-project.org/web/packages/patchwork/patchwork.pdf \
                  https://cran.r-project.org/web/packages/patchwork/vignettes/patchwork.html"
CMD["patchwork"]="$(r_cmd "patchwork")"
TEST["patchwork"]=1.1.3

URL["parallel"]="https://www.gnu.org/software/parallel/parallel_tutorial.pdf \
                 https://www.gnu.org/software/parallel/parallel.pdf \
                 https://www.gnu.org/software/parallel/parallel_cheat.pdf"
CMD["parallel"]="parallel --version"
TEST["parallel"]=20220322

URL["pillow"]="https://pillow.readthedocs.io/_/downloads/en/stable/pdf/"
CMD["pillow"]="python -c 'from PIL import __version__ as v; print(v)'"
TEST["pillow"]=10.0.0

URL["purrr"]="https://cran.r-project.org/web/packages/purrr/purrr.pdf \
              https://cran.r-project.org/web/packages/purrr/vignettes/base.html \
              https://cran.r-project.org/web/packages/purrr/vignettes/other-langs.html"
CMD["purrr"]="$(r_cmd "purrr")"
TEST["purrr"]=1.0.2

URL["python"]="https://docs.python.org/MAJOR.MINOR/archives/python-MAJOR.MINOR.PATCH-docs-pdf-letter.zip"
CMD["python"]="python --version"
TEST["python"]=3.10.3

URL["quadprog"]="https://cran.r-project.org/web/packages/quadprog/quadprog.pdf"
CMD["quadprog"]="$(r_cmd "quadprog")"
TEST["quadprog"]=1.5.8

URL["R"]="https://cran.r-project.org/doc/manuals/r-release/fullrefman.pdf"
CMD["R"]="R --version"
TEST["R"]=4.0.5

URL["r-cran-curl"]="https://cran.r-project.org/web/packages/curl/curl.pdf \
             https://cran.r-project.org/web/packages/curl/vignettes/intro.html \
             https://cran.r-project.org/web/packages/curl/vignettes/windows.html"
CMD["r-cran-curl"]="$(r_cmd "curl")"
TEST["r-cran-curl"]=5.0.2

URL["RColorBrewer"]="https://cran.r-project.org/web/packages/RColorBrewer/RColorBrewer.pdf"
CMD["RColorBrewer"]="$(r_cmd "RColorBrewer")"
TEST["RColorBrewer"]=1.1.3

URL["Rcpp"]="https://cran.r-project.org/web/packages/Rcpp/Rcpp.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-attributes.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-extending.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-introduction.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-jss-2011.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-libraries.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-modules.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-package.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-quickref.pdf \
             https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-sugar.pdf"
CMD["Rcpp"]="$(r_cmd "Rcpp")"
TEST["Rcpp"]=1.0.11

URL["RcppArmadillo"]="https://cran.r-project.org/web/packages/RcppArmadillo/RcppArmadillo.pdf \
                      https://cran.r-project.org/web/packages/RcppArmadillo/vignettes/RcppArmadillo-intro.pdf \
                      https://cran.r-project.org/web/packages/RcppArmadillo/vignettes/RcppArmadillo-sparseMatrix.pdf"
CMD["RcppArmadillo"]="$(r_cmd "RcppArmadillo")"
TEST["RcppArmadillo"]=0.12.6.1.0

URL["RcppEigen"]="https://cran.r-project.org/web/packages/RcppEigen/RcppEigen.pdf \
                  https://cran.r-project.org/web/packages/RcppEigen/vignettes/RcppEigen-Introduction.pdf"
CMD["RcppEigen"]="$(r_cmd "RcppEigen")"
TEST["RcppEigen"]=0.3.3.9.3

URL["readr"]="https://cran.r-project.org/web/packages/readr/readr.pdf \
              https://cran.r-project.org/web/packages/readr/vignettes/column-types.html \
              https://cran.r-project.org/web/packages/readr/vignettes/locales.html \
              https://cran.r-project.org/web/packages/readr/vignettes/readr.html"
CMD["readr"]="$(r_cmd "readr")"
TEST["readr"]=2.1.4

URL["reshape2"]="https://cran.r-project.org/web/packages/reshape2/reshape2.pdf"
CMD["reshape2"]="$(r_cmd "reshape2")"
TEST["reshape2"]=1.4.4

URL["rmarkdown"]="https://cran.r-project.org/web/packages/rmarkdown/rmarkdown.pdf"
CMD["rmarkdown"]="$(r_cmd "rmarkdown")"
TEST["rmarkdown"]=2.24

URL["rsync"]="https://download.samba.org/pub/rsync/rsync.1 \
              https://download.samba.org/pub/rsync/rsync-ssl.1 \
              https://download.samba.org/pub/rsync/rsyncd.conf.5 \
              https://download.samba.org/pub/rsync/rrsync.1"
CMD["rsync"]="rsync --version"
TEST["rsync"]=3.2.7

URL["rvest"]="https://cran.r-project.org/web/packages/rvest/rvest.pdf \
              https://cran.r-project.org/web/packages/rvest/vignettes/rvest.html \
              https://cran.r-project.org/web/packages/rvest/vignettes/starwars.html"
CMD["rvest"]="$(r_cmd "rvest")"
TEST["rvest"]=1.0.3

URL["scipy"]="https://docs.scipy.org/doc/scipy-MAJOR.MINOR.PATCH/scipy-html-MAJOR.MINOR.PATCH.zip"
CMD["scipy"]="python -c 'from scipy import __version__ as v; print(v)'"
TEST["scipy"]=1.8.0

URL["seaborn"]="https://github.com/seaborn/seaborn.github.io/archive/refs/tags/vMAJOR.MINOR.PATCH.zip"
CMD["seaborn"]="python -c 'from seaborn import __version__ as v; print(v)'"
TEST["seaborn"]=0.12.1

URL["sed"]="https://www.gnu.org/software/sed/manual/sed.pdf"
CMD["sed"]="sed --version"
TEST["sed"]=4.8

URL["scrapy"]="https://docs.scrapy.org/_/downloads/en/MAJOR.MINOR/pdf/"
CMD["scrapy"]="python -c 'from scrapy import __version__ as v; print(v)'"
TEST["scrapy"]=2.8

URL["sklearn"]="https://scikit-learn.org/MAJOR.MINOR/_downloads/scikit-learn-docs.zip"
CMD["sklearn"]="python -c 'from sklearn import __version__ as v; print(v)'"
TEST["sklearn"]=1.0.2

URL["ssh"]="https://man.openbsd.org/ssh \
            https://man.openbsd.org/sshd \
            https://man.openbsd.org/ssh_config \
            https://man.openbsd.org/sshd_config \
            https://man.openbsd.org/ssh-agent \
            https://man.openbsd.org/ssh-add \
            https://man.openbsd.org/sftp \
            https://man.openbsd.org/scp \
            https://man.openbsd.org/ssh-keygen \
            https://man.openbsd.org/sftp-server \
            https://man.openbsd.org/ssh-keyscan \
            https://man.openbsd.org/ssh-keysign"
CMD["ssh"]="ssh -V"
TEST["ssh"]=9.4p1

URL["stringr"]="https://cran.r-project.org/web/packages/stringr/stringr.pdf \
                https://cran.r-project.org/web/packages/stringr/vignettes/from-base.html \
                https://cran.r-project.org/web/packages/stringr/vignettes/regular-expressions.html \
                https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html"
CMD["stringr"]="$(r_cmd "stringr")"
TEST["stringr"]=1.5.0

URL["tar"]="https://www.gnu.org/software/tar/manual/tar.pdf"
CMD["tar"]="tar --version"
TEST["tar"]=1.35

URL["testthat"]="https://cran.r-project.org/web/packages/testthat/testthat.pdf"
CMD["testthat"]="$(r_cmd "testthat")"
TEST["testthat"]=3.1.10

URL["tibble"]="https://cran.r-project.org/web/packages/tibble/tibble.pdf"
CMD["tibble"]="$(r_cmd "tibble")"
TEST["tibble"]=3.2.1

URL["tidyr"]="https://cran.r-project.org/web/packages/tidyr/tidyr.pdf"
CMD["tidyr"]="$(r_cmd "tidyr")"
TEST["tidyr"]=1.3.0

URL["tidyverse"]="https://cran.r-project.org/web/packages/tidyverse/tidyverse.pdf"
CMD["tidyverse"]="$(r_cmd "tidyverse")"
TEST["tidyverse"]=2.0.0

URL["vegan"]="https://cran.r-project.org/web/packages/vegan/vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/decision-vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/diversity-vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/intro-vegan.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/partitioning.pdf \
              https://cran.r-project.org/web/packages/vegan/vignettes/FAQ-vegan.html"
CMD["vegan"]="$(r_cmd "vegan")"
TEST["vegan"]=2.6.4

URL["wget"]="https://www.gnu.org/software/wget/manual/wget.pdf"
CMD["wget"]="wget --version"
TEST["wget"]=1.21.3

URL["zsh"]="https://sourceforge.net/projects/zsh/files/zsh-doc/MAJOR.MINOR.PATCH/zsh-MAJOR.MINOR.PATCH-doc.tar.xz"
CMD["zsh"]="zsh --version"
TEST["zsh"]=5.8.1

export URL
export CMD
export TEST
