#! /bin/bash

declare -A URL
declare -A CMD
declare -A TEST

URL["armadillo"]="http://arma.sourceforge.net/docs.html"
CMD["armadillo"]="pkg-config --modversion armadillo"
TEST["armadillo"]=11.0.0

URL["awk"]="https://www.gnu.org/software/gawk/manual/gawk.pdf"
CMD["awk"]="awk --version"
TEST["awk"]=5.1.1

URL["bash"]="https://www.gnu.org/software/bash/manual/bash.pdf"
CMD["bash"]="bash --version"
TEST["bash"]=5.1.16

URL["bc"]="https://www.gnu.org/software/bc/manual/html_mono/bc.html"
CMD["bc"]="bc --version"
TEST["bc"]=1.07.1

URL["beautifulsoup"]="https://beautiful-soup-4.readthedocs.io/_/downloads/en/latest/pdf/"
CMD["beautifulsoup"]="python -c 'from bs4 import __version__ as v; print(v)'"
TEST["beautifulsoup"]=4.12.2

URL["beets"]="https://beets.readthedocs.io/_/downloads/en/vMAJOR.MINOR.PATCH/pdf/"
CMD["beets"]="python -c 'from beets import __version__ as v; print(v)'"
TEST["beets"]=1.6.0

URL["biopython"]="https://biopython.org/DIST/docs/tutorial/Tutorial-MAJOR.MINOR.pdf"
CMD["biopython"]="python -c 'from Bio import __version__ as v; print(v)'"
TEST["biopython"]=1.79

URL["black"]="https://black.readthedocs.io/_/downloads/en/latest/htmlzip/"
CMD["black"]="python -c 'from black import __version__ as v; print(v)'"
TEST["black"]=23.7.0

URL["coreutils"]="https://www.gnu.org/software/coreutils/manual/coreutils.pdf"
CMD["coreutils"]="ls --version"
TEST["coreutils"]=9.0

URL["eigen"]="https://eigen.tuxfamily.org/dox/eigen-doc.tgz"
CMD["eigen"]="pkg-config --modversion eigen3"
TEST["eigen"]=3.4.0

URL["ffmpeg"]="https://ffmpeg.org/ffmpeg-all.html"
CMD["ffmpeg"]="ffmpeg -version"
TEST["ffmpeg"]=5.0

URL["find"]="https://www.gnu.org/software/findutils/manual/find.pdf"
CMD["find"]="find --version"
TEST["find"]=4.9.0

URL["fish"]="https://fishshell.com/docs/MAJOR.MINOR/index.html \
             https://fishshell.com/docs/MAJOR.MINOR/tutorial.html"
CMD["fish"]="fish --version"
TEST["fish"]=3.3.1

URL["gcc"]="https://gcc.gnu.org/onlinedocs/gcc-MAJOR.MINOR.0/gcc.pdf \
            https://gcc.gnu.org/onlinedocs/gcc-MAJOR.MINOR.0/libstdc++-manual.pdf.gz"
CMD["gcc"]="gcc --version"
TEST["gcc"]=11.2.0

URL["gimp"]="https://download.gimp.org/pub/gimp/help/gimp-help-MAJOR.MINOR.0.tar.bz2"
CMD["gimp"]="gimp --version"
TEST["gimp"]=2.10.30

URL["graphviz"]=""
CMD["graphviz"]="dot -V"
TEST["graphviz"]=3.0.0

URL["inkscape"]="https://inkscape-manuals.readthedocs.io/_/downloads/en/latest/pdf/"
CMD["inkscape"]="inkscape --version"
TEST["inkscape"]=1.1.2

URL["gitpython"]="https://gitpython.readthedocs.io/_/downloads/en/MAJOR.MINOR.PATCH/pdf/"
CMD["gitpython"]="python -c 'from git import __version__ as v; print(v)'"
TEST["gitpython"]=3.1.32

URL["julia"]="https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-MAJOR.MINOR.PATCH.pdf"
CMD["julia"]="julia --version"
TEST["julia"]=1.7.2

URL["lua"]="https://www.lua.org/ftp/refman-MAJOR.MINOR.tar.gz"
CMD["lua"]="lua -v"
TEST["lua"]=5.4

# URL["magic"]="https://magic.readthedocs.io/_/downloads/en/stable/pdf/"
# CMD["magic"]="python -c 'import magic; print(magic.version())'"
# TEST["magic"]=0.4.27

URL["matplotlib"]="https://matplotlib.org/MAJOR.MINOR.PATCH/Matplotlib.pdf"
CMD["matplotlib"]="python -c 'from matplotlib import __version__ as v; print(v)'"
TEST["matplotlib"]=3.5.1

URL["mpi4py"]="https://mpi4py.readthedocs.io/_/downloads/en/MAJOR.MINOR.PATCH/pdf/"
CMD["mpi4py"]="python -c 'from mpi4py import __version__ as v; print(v)'"
TEST["mpi4py"]=3.1.4

URL["nodejs"]="https://nodejs.org/docs/latest-vMAJOR.x/api/all.html"
CMD["nodejs"]="node --version"
TEST["nodejs"]=17.8.0

URL["numpy"]="https://numpy.org/doc/MAJOR.MINOR/numpy-html.zip"
CMD["numpy"]="python -c 'from numpy import __version__ as v; print(v)'"
TEST["numpy"]=1.22

URL["octave"]="https://octave.org/doc/octave-MAJOR.MINOR.PATCH.pdf"
CMD["octave"]="octave --version"
TEST["octave"]=6.4.0

URL["pandas"]="https://pandas.pydata.org/pandas-docs/version/MAJOR.MINOR.PATCH/pandas.zip"
CMD["pandas"]="python -c 'from pandas import __version__ as v; print(v)'"
TEST["pandas"]=1.4.1

URL["parallel"]="https://www.gnu.org/software/parallel/parallel_tutorial.pdf \
                 https://www.gnu.org/software/parallel/parallel.pdf \
                 https://www.gnu.org/software/parallel/parallel_cheat.pdf"
CMD["parallel"]="parallel --version"
TEST["parallel"]=20220322

URL["pillow"]="https://pillow.readthedocs.io/_/downloads/en/stable/pdf/"
CMD["pillow"]="python -c 'from PIL import __version__ as v; print(v)'"
TEST["pillow"]=10.0.0

URL["python"]="https://docs.python.org/MAJOR.MINOR/archives/python-MAJOR.MINOR.PATCH-docs-pdf-letter.zip"
CMD["python"]="python --version"
TEST["python"]=3.10.3

URL["rust"]=""
CMD["rust"]="rustc --version"
TEST["rust"]=1.61.0

URL["r"]="https://cran.r-project.org/doc/manuals/r-release/fullrefman.pdf"
CMD["r"]="R --version"
TEST["r"]=4.0.5

URL["scipy"]="https://docs.scipy.org/doc/scipy-MAJOR.MINOR.PATCH/scipy-html-MAJOR.MINOR.PATCH.zip"
CMD["scipy"]="python -c 'from scipy import __version__ as v; print(v)'"
TEST["scipy"]=1.8.0

URL["seaborn"]="https://github.com/seaborn/seaborn.github.io/archive/refs/tags/vMAJOR.MINOR.PATCH.zip"
CMD["seaborn"]="python -c 'from seaborn import __version__ as v; print(v)'"
TEST["seaborn"]=0.12.1

URL["sed"]="https://www.gnu.org/software/sed/manual/sed.pdf"
CMD["sed"]="sed --version"
TEST["sed"]=4.8

URL["scrapy"]="https://docs.scrapy.org/_/downloads/en/MAJOR.MINOR/pdf/"
CMD["scrapy"]="python -c 'from scrapy import __version__ as v; print(v)'"
TEST["scrapy"]=2.8

URL["sklearn"]="https://scikit-learn.org/MAJOR.MINOR/_downloads/scikit-learn-docs.zip"
CMD["sklearn"]="python -c 'from sklearn import __version__ as v; print(v)'"
TEST["sklearn"]=1.0.2

URL["wget"]="https://www.gnu.org/software/wget/manual/wget.pdf"
CMD["wget"]="wget --version"
TEST["wget"]=1.21.3

URL["zsh"]="https://sourceforge.net/projects/zsh/files/zsh-doc/MAJOR.MINOR.PATCH/zsh-MAJOR.MINOR.PATCH-doc.tar.xz"
CMD["zsh"]="zsh --version"
TEST["zsh"]=5.8.1

export URL
export CMD
export TEST
